### ISSUE TITLE
dependencies (like protobuff) should be shaded

### ISSUE THREAD

**Issue by ravenAtSafe** [olavloite/spanner-jdbc#1]
spanner-jdbc depends on a different version of protobuff than my application already bundles.  If the "fat" spanner-jdbc jar shaded its dependencies I could safely use this driver.

**Comment by olavloite** [comment]
The problem with shading some of these dependencies is that some of them do initialization and class loading by hard coded class names, such as for example JettyTlsUtil:

  /**
   * Indicates whether or not the Jetty ALPN jar is installed in the boot classloader.
   */
  static boolean isJettyAlpnConfigured() {
    try {
      Class.forName("org.eclipse.jetty.alpn.ALPN", true, null);
      return true;
    } catch (ClassNotFoundException e) {
      return false;
    }
  }

**Comment by olavloite** [comment]
Shading the dependencies for the driver unfortunately does not work out of the box, as netty-tcnative does not seem to support shading.

**Comment by olavloite** [comment]
As of version 0.6 a thick jar with shaded dependencies is available. The only exception is the abovementioned netty-tcnative dependency. This dependency does not seem to support shading, as the dynamic loading of the native component fails when the classes are shaded.
