### ISSUE TITLE
Order of columns in delete-statement need to be in primary-key-order

### ISSUE THREAD

**Issue by smec-cgint** [olavloite/spanner-jdbc#10]
I like the possibility to use google cloud spanner via jdbc for reading and writing! a lot!

The thing I ran into is that in delete-statements I need to specify the primary-key-columns of the query in spanner-key-order and this is not done by the spring-repository.
So I end up getting errors that the data-types do not match because the order does not match.

Do you see any possibility that the driver orders the columns in the deletes where-clause in spanner-key-order automatically ?
This would be a great benefit also when the driver is used in a query tool so that also humans doing sql-queries do not have to mind the key-order.

**Comment by olavloite** [comment]
Fixed in 0.15 by fetching the primary key of the table from the database metadata. This does however mean that there is an extra query needed once for getting the PK information from the database when a delete-srtatement is issued. The result is then cached to avoid subsequent metadata queries.
