### ISSUE TITLE
Perform an upsert in case of 'on duplicate key update'

### ISSUE THREAD

**Issue by smec-cgint** [olavloite/spanner-jdbc#11]
We are currently using MySQL and have the option to save items that are automatically inserted or updated using 'on duplicate key update' in the insert statement.

In this case it would be nice if the driver would issue an InsertOrUpdate-mutation against cloud spanner.

**Comment by olavloite** [comment]
I'll have a look to see if it's feasible.

**Comment by olavloite** [comment]
As of version 0.15 the 'INSERT INTO MYTABLE (COL1, COL2, COL3, ...) VALUES (VAL1, VAL2, VAL3, ...) ON DUPLICATE KEY UPDATE COL2=VAL2, COL3=VAL3, ...' is supported.

However, there is a catch: Google Cloud Spanner does support an INSERT-OR-UPDATE command to be sent. It does however not support different values for the INSERT or UPDATE part to be specified. The driver therefore ignores all values specified in the UPDATE-part of the statement and uses only the values specified in the VALUES-part of the INSERT-statement.
