### ISSUE TITLE
Create table result in UPPERCASE letters

### ISSUE THREAD

**Issue by shlomiw** [olavloite/spanner-jdbc#13]
Hi,

First of all - **amazing** work! gonna make my life with spanner so much easier!

I've integrated your library with **DBeaver** and I got full IDE controlling my tables, queries, scripts - and now with updates/inserts and bulk updates/inserts etc - amazing!!

One question though, I've tried to create a table, and from some reason in resulted in UPPERCASE letters.
The statement:
```
CREATE TABLE TestTableViaDBeaver(
 TestId INT64 NOT NULL,
 Foo STRING(10) 
) PRIMARY KEY (TestId);
```

It did create the table but both the table name and the columns are UPPERCASED, why?

![image](https://user-images.githubusercontent.com/1025170/33459150-982a2a0e-d631-11e7-999f-32a5d3395967.png)

Thanks in advance,
Shlomi

**Comment by ravenAtSafe** [comment]
I never quite got satisfaction on this in #3 either.

**Comment by shlomiw** [comment]
@ravenAtSafe - tnx for pointing this out. I just tried the backticks suggested there but it still in UPPERCASE.
Executing the same query via Google's spanner admin client results with the correct letters case (`TestTableViaDBeaver`)

**Comment by olavloite** [comment]
This will be fixed in the next release. The driver does some formatting of certain specific DDL-statements generated by JPA/Hibernate. This converted all DDL-statements to upper case. This has been changed so that only the specific DDL-statements are converted, and all other DDL-statement are passed directly to Cloud Spanner.

**Comment by shlomiw** [comment]
@olavloite - thanks!
Can you tell when the next release will be out? I was hoping using your driver for migration scripts next week.

**Comment by olavloite** [comment]
@shlomiw I'll be making a new release somewhere this weekend.

**Comment by shlomiw** [comment]
Perfect! thank you very much for the great work!

**Comment by shlomiw** [comment]
FYI - I did a quick code update in your source at `formatDDLStatement()`, and now the DDL executes without the uppercase.. so no hurry, please take your time.
I'll be keeping track on your next releases.
Many many thanks!
