### ISSUE TITLE
Error parsing comment before DDL statement

### ISSUE THREAD

**Issue by shlomiw** [olavloite/spanner-jdbc#14]
Very small issue:
In a script if I add a comment before DDL statement, it throws SQL script execution.
(without the comment the script executes fine)

![image](https://user-images.githubusercontent.com/1025170/33524484-c6a99a62-d826-11e7-8af7-74069f27cc42.png)

**Comment by olavloite** [comment]
Fixed in 0.20. Comments in DDL-statements will no longer be sent to Cloud Spanner, as Cloud Spanner itself does not accept these as a part of a DDL-statement.

**Comment by shlomiw** [comment]
Great! Thanks
