### ISSUE TITLE
Insert multiple rows?

### ISSUE THREAD

**Issue by shlomiw** [olavloite/spanner-jdbc#19]
Hi,

Is there a way to bulk multiple insert as in SQL server:
```
INSERT INTO MyTable ( Column1, Column2 ) VALUES
( Value1, Value2 ), ( Value1, Value2 )
```

Thanks

**Comment by olavloite** [comment]
This should work:

INSERT INTO MyTable (Column1, Column2)
SELECT Value1, Value2
UNION ALL
SELECT Value3, Value4
UNION ALL
...

**Comment by shlomiw** [comment]
It does work, thanks
