### ISSUE TITLE
debug logging should not be on by default

### ISSUE THREAD

**Issue by ravenAtSafe** [olavloite/spanner-jdbc#2]
When using spanner-jdbc there are many lines output like the following:

> Jun 12, 2017 9:14:41 AM io.grpc.internal.ManagedChannelImpl <init>
> INFO: [ManagedChannelImpl@3246fb96] Created with target spanner.googleapis.com:443

Could they be suppressed, or controlled by a flag?

**Comment by olavloite** [comment]
Log levels are configured using a standard Java Logging properties file and specifying the properties file as a VM argument when starting the application. I have attached an example properties file that suppresses the INFO messages from the Google CloudSpanner API.

**Comment by olavloite** [comment]
handlers					= java.util.logging.ConsoleHandler
nl.topicus.level			= INFO
io.grpc.internal.level		= WARNING
java.util.logging.SimpleFormatter.format=%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$s %2$s %5$s%6$s%n

**Comment by olavloite** [comment]
I have added some logic that changes the default logging level of the VM if no logging configuration has been provided.
