### ISSUE TITLE
Update with Join

### ISSUE THREAD

**Issue by shlomiw** [olavloite/spanner-jdbc#25]
Hi,

How do I update a table with join on other table for where filtering?

i.e. activate all users from a specific country (in this example, his address is in a different table)

update Users
set Active = true
from Users as U
inner join UserAddresses as UA on U.UserId = UA.UserId
where UA.CountryCode = "US"

thanks in advance

**Comment by olavloite** [comment]
The driver (currently) does not support update statements containing joins. What you can do however is make use of the INSERT INTO ... ON DUPLICATE KEY UPDATE feature for these kind of queries. In this specific example it should be something like this:

```sql
INSERT INTO Users
(UserId, Active)
SELECT UserId, true
FROM Users as U
INNER JOIN UserAddresses as UA on U.UserId = UA.UserId
WHERE UA.CountryCode = "US"
ON DUPLICATE KEY UPDATE
```
This will create a set of insertOrUpdate mutations that in the end will all be updates as you only select existing UserId's.

**Comment by shlomiw** [comment]
Hi,
I was also considering this approach before asking you, my question - can I put in the Insert/Select only the relevant columns to update? (i.e in this case the Key - UserId and Active column).
Of course Users table can have many more columns..

Thanks in advance

**Comment by olavloite** [comment]
Yep, that shouldn't be a problem as long as you only include existing rows in your query part of the statement (or the columns that you don't specify are all nullable).

**Comment by shlomiw** [comment]
I understand, I'll try it out 👍
