### ISSUE TITLE
How to work with lower case identifier names?

### ISSUE THREAD

**Issue by ravenAtSafe** [olavloite/spanner-jdbc#3]
It doesn't appear to respect quoting for case sensitive identifiers (`rk` is the same as RK, at least for CREATE TABLE).  And standard SQL identifier quoting like "rk" breaks the SQL parser.

**Comment by olavloite** [comment]
Identifiers must be quoted using backticks ( ` ), see also this part of the documentation of Google CloudSpanner: https://cloud.google.com/spanner/docs/lexical#identifiers. These backticks are also accepted by the SQL Parser of the JDBC Driver.

**Comment by ravenAtSafe** [comment]
Here is an example of a create table statement in which we quote both the table and column name, yet the Google admin tool shows them all in upper case.  It is possible to **manually** create tables with mixed case identifiers (well, case-insensitive, case-preserving).

```
create table `SomeTableName` (
`creation_instance` int64
) PRIMARY KEY (creation_instance)

```
Is this just a limitation of the API the driver is using?
