### ISSUE TITLE
Cannot deploy to cluster with version of 1.0.2

### ISSUE THREAD

**Issue by minhdqvn** [olavloite/spanner-jdbc#50]
at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[na:1.8.0_162]
java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_162]
nl.topicus.jdbc.CloudSpannerDriver.connect(CloudSpannerDriver.java:22) ~[spanner-jdbc-1.0.2.jar!/:na]
nl.topicus.jdbc.CloudSpannerDriver.connect(CloudSpannerDriver.java:124) ~[spanner-jdbc-1.0.2.jar!/:na]
assessment-service | Apr 23, 2018, 4:40:47 PM | at nl.topicus.jdbc.CloudSpannerConnection.<init>(CloudSpannerConnection.java:239) ~[spanner-jdbc-1.0.2.jar!/:na]
nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl.getDatabaseClient(SpannerImpl.java:288) ~[spanner-jdbc-1.0.2.jar!/:na]
nl.topicus.jdbc.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[spanner-jdbc-1.0.2.jar!/:na]
assessment-service | Apr 23, 2018, 4:40:47 PM | Caused by: java.lang.IllegalStateException: Cloud Spanner client has been closed

**Comment by olavloite** [comment]
@minhdqvn Do you have any additional information about what exactly it is you are doing? What kind of cluster are we talking about?

**Comment by olavloite** [comment]
I have an idea what is causing this problem, and I will try to make a fix for this by the end of the day/evening (Central European Time)

**Comment by minhdqvn** [comment]
@olavloite I have debugged with your code.
First round, I have create an entityManager with Spanner datasource --> Spanner Driver close method is triggered, so Spanner object got closed status. (I'm confusing with closed variable is still FALSE).
Second round, Application makes a connection again. An exception is thrown due to Spanner is closed.

**Comment by olavloite** [comment]
This problem should now be fixed in 1.0.3. I just built a new release, but it might take a couple of hours before the version is available on Maven central. In the meantime, you could download it directly from Github (check the Releases page).
