### ISSUE TITLE
Is an Array datatype supported for inserts

### ISSUE THREAD

**Issue by holen1master** [olavloite/spanner-jdbc#56]
I am using Squirrel 3.8.1.   I am not able to insert a row into a table that has an column defined as an array of strings.  Here's my test script.  Please advise.  Thx

drop table if exists product_view_dave ;
 
CREATE TABLE product_view_dave (
                product_view_id STRING(37) NOT NULL,
                site_filter ARRAY<STRING(37)>,
) PRIMARY KEY (product_view_id)
;
/* this insert fails*/ 
insert into product_view_dave
(product_view_id, site_filter) values ('2342',['3','4']) ;
 
insert into product_view_dave
(product_view_id) values ('2342') ;

select * from product_view_dave;

**Comment by olavloite** [comment]
Array data types were only supported through JDBC parameters and not as literals. This has now (version 1.0.7) been added. Array literals must be specified in the 'old' PostgreSQL format, i.e. as string literals containing curly braces. Strings (and date and timestamps) within an array literal must be between double quotes. Examples:

```
insert into product_view_dave
(product_view_id, site_filter) values ('2342', '{ "3", "4" }' ) ;
```

```
insert into foo (bool_values) values ('{true, false, true}');
insert into foo (int64_values) values ('{1,2,3}');
insert into foo (float64_values) values ('{1.0, 2.5, 4.999999}');
insert into foo (date_values) values ('{ {d "2018-05-20"}, {d "2018-05-21"} }');
insert into foo (timestamp_values) values ('{ {ts "2018-05-20 10:00:00"}, {ts "2018-05-21 15:03:10.12345"} }');
```

**Comment by holen1master** [comment]
Hi olavloite,

I installed this new version of the driver (using squirrel 38.1) but I still am receiving an error when running:

insert into product_view_dave
(product_view_id, site_filter) values ('2342','['3','4']') ;

Error:
nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerException: FAILED_PRECONDITION: nl.topicus.jdbc.shaded.io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Invalid value for column site_filter in table product_view_dave: Expected STRING.

It also appears the fix for issue #58 does not work either.  Perhaps I installed the new driver incorrectly.  Please advise.  Thx!

**Comment by holen1master** [comment]
I actually copied the wrong test case into the comment.  I am using your test case and still receive the error.  I am thinking that the new driver is not installed properly in squirrel 3.8.1 since issue#58 is not working either.  To install the new jar in Squirrel, I just removed the old jar file and put in the new driver in the same directory as the old jar.  Then I  changed the existing driver to use the new jar.  I  also created a new driver using the new jar.  I closed and reopened squirrel.   I could not get either to work.  Any ideas?

**Comment by holen1master** [comment]
I figured out the problem.   A copy of the  JDBC driver was in 2 directories that squirrel utilizes.  I removed both copies of the old jar and placed the new jar in only one of the directories that squirrel utilizes.  Both issues 56 and 58 are confirm to work.  Thx for getting these fixed so quick!!
