### ISSUE TITLE
SQLException not being thrown when trying to select from a table that doesn't exist

### ISSUE THREAD

**Issue by jpoernomoatsafe** [olavloite/spanner-jdbc#73]
Hi Knut, 

so we have a set up such as this:
```
      try (Statement schemaScanStmt = createStatement())
      {
         try
         {
            ResultSet schemaScanResult = schemaScanStmt.executeQuery("SELECT * FROM TABLE_DOESNT_EXIST WHERE 1=0");
         } catch (SQLException e)
         {
            log.error("table doesn't exist!");
            return;
         }
         ResultSetMetaData schemaScanMetadata = schemaScanResult.getMetaData();
         ... // do stuff 
      }
```

but we're noticing that we're not getting a SQLException when we execute the query

What happens instead:
SQLException is not thrown on `schemaScanStmt.executeQuery()" and 
`SpannerException` (a runtime exception) is thrown on `schemaScanResult.getMetaData()` 

Shouldn't a SQLException be thrown when executing an erroneous SQL statement?

This is happening with spanner-jdbc-1.0.8 

Thanks!

**Comment by olavloite** [comment]
You're absolutely right that the `ResultSet#getMetaData` method should throw a `SQLException` in this case.

The reason that `Statement#executeQuery(String)` does not throw a `SQLException` is that the JDBC driver (or actually the underlying Spanner Java library supplied by Google) does not execute the query on Cloud Spanner before any data is actually requested. As the methods `ResultSet#next` and `ResultSet#getMetaData` do request data, these are the methods that are throwing the exception in this case. I am considering changing that behavior in the JDBC driver, and let the driver execute the statement directly when the `Statement#executeQuery(String)` is called, as this is what most developers would expect. The performance gain by waiting to execute the query until any data is actually requested is in my opinion negligible, as there are almost no use cases where a developer would call `Statement#executeQuery` without ever doing anything with the result of that.

**Comment by olavloite** [comment]
Fixed for 1.0.9.

**Comment by olavloite** [comment]
I'll make a new issue and see if I could change the behavior of `Statement#executeQuery(String)` into actually executing the query right away, but I'll schedule that for version 1.1.x as it might introduce a breaking change for those who might actually rely on the current behavior.

**Comment by jpoernomoatsafe** [comment]
excellent! thanks!
