### ISSUE TITLE
 precision (maximum length) of a string (MAX) column in ResultSetMetaData is always zero

### ISSUE THREAD

**Issue by jpoernomoatsafe** [olavloite/spanner-jdbc#76]
this issue relates to #65 

the original issue seems to have been fixed for the most part. precision (maximum length) for most string columns are being reported accurately within `ResultSetMetaData`

However, string(max) columns still have some issues, in which they are reported to have a display size of 50 and precision of 0 within `ResultSetMetaData`

version: 1.0.8

**Comment by jpoernomoatsafe** [comment]
this was using quoted table names

**Comment by olavloite** [comment]
Fixed for version 1.0.9.
