### ISSUE TITLE
Improve logging for rejected queries

### ISSUE THREAD

**Issue by ravenAtSafe** [olavloite/spanner-jdbc#8]
Could we get better feedback when queries are rejected?  Currently we have just have to squint at them and try to figure out what is wrong.

Example 1: Parsing fails (falsely, as noted in https://github.com/olavloite/spanner-jdbc/issues/7)

```
create table `SomeTableName` (
`creation_instance` int64
) PRIMARY KEY (`creation_instance`)
java.sql.SQLException: Error while parsing sql statement
```

Example 2: Duplicate table rejected by Google

```
create table `SomeTableNameThatAlreadyExists` (
`creation_instance` int64
) PRIMARY KEY (creation_instance)
java.sql.SQLException: Could not execute DDL statement
```

**Comment by olavloite** [comment]
#JSQLParser/JSqlParser#491

**Comment by olavloite** [comment]
Cause of an exception has been added to the exception message as of version 0.12.
