### ISSUE TITLE
Support reading arrays

### ISSUE THREAD

**Issue by ravenAtSafe** [olavloite/spanner-jdbc#9]
One of the few remaining deficiencies of this driver compared to the official one is support for reading arrays.

Ideally they would be reported as java.sql.Types.ARRAY rather than java.sql.Types.OBJECT, and ResultSet.getArray() would work.

(Writing would be great too, but I'm not sure my company will take advantage of that feature anytime soon.)

**Comment by olavloite** [comment]
Support for both reading and writing arrays is added in version 0.13.
